name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: arjsh16
          outputs: |
            dist/github-snake.gif?color_snake=#6495ed&color_dots=#161b22,#2a2a3a,#ffb3c6,#FA96B0,#d4607a
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
